"""
Topology scan: C_l for all finite quotients S^3/Gamma.

Scans the ADE classification of finite subgroups Gamma < SU(2) to find
which topology S^3/Gamma best matches the Planck CMB quadrupole D_2 = 201 muK^2.

The finite subgroups of SU(2) (ADE classification):
  - Cyclic:             Z_n  (order n),  for n >= 1
  - Binary dihedral:    D*_n (order 4n), for n >= 2
  - Binary tetrahedral: T*   (order 24)
  - Binary octahedral:  O*   (order 48)
  - Binary icosahedral: I*   (order 120)

For each Gamma, the multiplicity of Gamma-invariant vectors in the
(k+1)-dimensional irrep V_{k/2} of SU(2) is:

    r_Gamma(k) = (1/|Gamma|) * sum_{g in Gamma} chi_{k/2}(g)

where chi_j(theta) = sin((2j+1)*theta/2) / sin(theta/2) is the SU(2)
character at rotation angle theta.

The total number of Gamma-invariant scalar harmonics at level k is
r_Gamma(k) * (k+1), where the factor (k+1) comes from the SU(2)_R
representation (left Clifford quotient preserves SU(2)_R).

The CMB angular power spectrum on S^3/Gamma is computed via the
suppression ratio:

    S_l = C_l^{Gamma} / C_l^{S^3}
        = [sum_nu T_l(nu)^2 * r_Gamma(nu-1) * nu] / [sum_nu T_l(nu)^2 * nu^2]

where T_l(nu) is the CAMB Boltzmann transfer function (topology-independent),
nu = k+1 is the eigenmode index, and the weight r_Gamma(k) * nu counts
the total Gamma-invariant scalar harmonics.

NUMERICAL: Topology scan across all ADE subgroups of SU(2).

References:
    - Cornish, Spergel, Starkman, CQG 15, 2657 (1998)
    - Aurich, Lustig, Steiner, CQG 22, 2061 (2005)
    - Luminet et al., Nature 425, 593 (2003)
    - COMPACT Collaboration, A&A 683, A62 (2024)
"""

import numpy as np

try:
    import camb
    HAS_CAMB = True
except ImportError:
    HAS_CAMB = False


# ===================================================================
# SU(2) character
# ===================================================================

def character_su2(k, theta):
    """
    Character of V_{k/2} (dimension k+1) at rotation angle theta.

    chi_{k/2}(theta) = sin((k+1)*theta/2) / sin(theta/2)

    Special cases handled via L'Hopital:
      theta = 0:    chi = k + 1
      theta = 2*pi: chi = (-1)^k * (k + 1)

    Parameters
    ----------
    k : int
        Level index (non-negative). Representation has dimension k+1.
    theta : float
        Rotation angle in [0, 2*pi].

    Returns
    -------
    float : character value
    """
    half = theta / 2.0
    sin_denom = np.sin(half)

    if abs(sin_denom) < 1e-14:
        # L'Hopital: lim sin((k+1)x)/sin(x) = (k+1)*cos((k+1)x)/cos(x)
        cos_num = np.cos((k + 1) * half)
        cos_denom = np.cos(half)
        if abs(cos_denom) < 1e-14:
            # theta = pi: use exact formula
            return np.sin((k + 1) * np.pi / 2) / np.sin(np.pi / 2)
        return (k + 1) * cos_num / cos_denom

    return np.sin((k + 1) * half) / sin_denom


# ===================================================================
# Conjugacy classes for all ADE subgroups of SU(2)
# ===================================================================

def conjugacy_classes_cyclic(n):
    """
    Conjugacy classes of Z_n in SU(2).

    Z_n is generated by g = diag(e^{2*pi*i/n}, e^{-2*pi*i/n}),
    which has SU(2) rotation angle theta = 4*pi/n.
    The s-th power g^s has angle theta_s = 4*pi*s/n.

    g^n = I (not -I), so this is genuinely order n.
    Z_n is abelian, so each element is its own conjugacy class.

    The quotient S^3/Z_n is the lens space L(n, 1).

    Returns
    -------
    list of (size, theta) : conjugacy classes
    int : group order
    """
    classes = []
    for s in range(n):
        theta = 4 * np.pi * s / n
        classes.append((1, theta))
    return classes, n


def conjugacy_classes_binary_dihedral(n):
    """
    Conjugacy classes of the binary dihedral group D*_n (order 4n).

    D*_n < SU(2) is generated by:
      a = diag(e^{i*pi/n}, e^{-i*pi/n})  (order 2n in SU(2), theta = 2*pi/n)
      b = [[0, i], [i, 0]]               (order 4, theta = pi, b^2 = -I = a^n)

    Elements: {a^s : s = 0..2n-1} union {a^s*b : s = 0..2n-1}, total 4n.

    The SU(2) rotation angles are:
      a^s has eigenvalues e^{i*s*pi/n}, e^{-i*s*pi/n}, hence theta = 2*pi*s/n.
      a^s*b has trace 0 (since b is off-diagonal), hence theta = pi.

    Conjugacy classes:
      1. {e}:                             1 element, theta = 0
      2. {a^n} = {-I}:                    1 element, theta = 2*pi
      3. {a^s, a^{2n-s}} for s=1..n-1:   n-1 classes of size 2, theta = 2*pi*s/n
      4. n even: two reflection classes of size n, both at theta = pi
         n odd:  one reflection class of size 2n, at theta = pi

    Parameters
    ----------
    n : int >= 2
        The index in D*_n. Group order is 4n.

    Returns
    -------
    list of (size, theta) : conjugacy classes
    int : group order (4n)
    """
    classes = []

    # Identity
    classes.append((1, 0.0))
    # Central element -I (= a^n, theta = 2*pi*n/n = 2*pi)
    classes.append((1, 2 * np.pi))

    # Rotation classes: {a^s, a^{2n-s}} for s = 1, ..., n-1
    # a^s has theta = 2*pi*s/n
    for s in range(1, n):
        theta = 2 * np.pi * s / n
        classes.append((2, theta))

    # Reflection classes: all elements a^s * b have trace 0, theta = pi
    # n even: two classes of size n
    # n odd: one class of size 2n
    if n % 2 == 0:
        classes.append((n, np.pi))
        classes.append((n, np.pi))
    else:
        classes.append((2 * n, np.pi))

    order = 4 * n

    # Verify
    total = sum(s for s, _ in classes)
    assert total == order, f"D*_{n}: classes sum to {total}, expected {order}"

    return classes, order


def conjugacy_classes_binary_tetrahedral():
    """
    Conjugacy classes of the binary tetrahedral group T* (order 24).

    T* < SU(2) is the preimage of the tetrahedral rotation group T (order 12).
    As quaternions: 8 from Q_8 (+-1, +-i, +-j, +-k) plus 16 half-integer
    quaternions (+-1/2, +-1/2, +-1/2, +-1/2).

    T* has 7 conjugacy classes, but only 5 distinct trace values.
    For the character formula, only the trace (= rotation angle) matters,
    so we use 5 trace-grouped classes:

      1. {e}:     1 element,  theta = 0     (tr = +2)
      2. {-e}:    1 element,  theta = 2*pi  (tr = -2)
      3. C3:      8 elements, theta = 2*pi/3  (tr = +1)
      4. C3inv:   8 elements, theta = 4*pi/3  (tr = -1)
      5. C2:      6 elements, theta = pi     (tr = 0, the +-i, +-j, +-k)

    Total: 1 + 1 + 8 + 8 + 6 = 24.

    Returns
    -------
    list of (size, theta) : conjugacy classes (grouped by trace)
    int : 24
    """
    classes = [
        (1,  0.0),               # Identity
        (1,  2 * np.pi),         # -Identity
        (8,  2 * np.pi / 3),     # Order 3 rotations (tr = +1)
        (8,  4 * np.pi / 3),     # Inverse rotations (tr = -1)
        (6,  np.pi),             # Order 2 rotations (tr = 0)
    ]
    order = 24
    total = sum(s for s, _ in classes)
    assert total == order, f"T*: classes sum to {total}, expected {order}"
    return classes, order


def conjugacy_classes_binary_octahedral():
    """
    Conjugacy classes of the binary octahedral group O* (order 48).

    O* < SU(2) is the preimage of the octahedral rotation group O (order 24).

    Conjugacy classes (8 classes):
      1. {e}:     1 element,  theta = 0
      2. {-e}:    1 element,  theta = 2*pi
      3. C4_a:    6 elements, theta = pi/2   (order-4 face rotations, lifted)
      4. C4_b:    6 elements, theta = 3*pi/2 (inverses)
      5. C3_a:    8 elements, theta = 2*pi/3 (order-3 vertex rotations, lifted)
      6. C3_b:    8 elements, theta = 4*pi/3 (inverses)
      7. C2:     12 elements, theta = pi     (order-2 edge rotations, lifted)
      8. C6:      6 elements, theta = pi     (from squares of C4, but wait...)

    Actually, more carefully using the character table of O*:
      1. {e}:      1 element, theta = 0
      2. {-e}:     1 element, theta = 2*pi
      3. C8_a:     6 elements, theta = pi/4  (order-8 elements)
      4. C8_b:     6 elements, theta = 7*pi/4 (= 2*pi - pi/4, inverses)
      5. C4:       6 elements, theta = pi/2  (order-4 face rotations)
                   -- wait, this is C8^2, angle pi/2
      6. C6_a:     8 elements, theta = 2*pi/3 (vertex rotations)
      7. C6_b:     8 elements, theta = 4*pi/3 (inverses)
      8. C2:      12 elements, theta = pi     (edge rotations)

    Total: 1+1+6+6+6+8+8+12 = 48. Check.

    Returns
    -------
    list of (size, theta) : conjugacy classes
    int : 48
    """
    classes = [
        (1,  0.0),                  # Identity
        (1,  2 * np.pi),            # -Identity
        (6,  np.pi / 2),            # Order 8 elements (face rotation lifts)
        (6,  3 * np.pi / 2),        # Inverses
        (6,  np.pi),                # Squares of C8 (order 4)
        (8,  2 * np.pi / 3),        # Vertex rotations (order 6)
        (8,  4 * np.pi / 3),        # Inverses
        (12, np.pi),                # Edge rotations (order 4)
    ]
    order = 48
    total = sum(s for s, _ in classes)
    assert total == order, f"O*: classes sum to {total}, expected {order}"
    return classes, order


def conjugacy_classes_binary_icosahedral():
    """
    Conjugacy classes of the binary icosahedral group I* (order 120).

    Same as in poincare_homology.py. 9 conjugacy classes.

    Returns
    -------
    list of (size, theta) : conjugacy classes
    int : 120
    """
    classes = [
        (1,  0.0),                      # Identity
        (1,  2 * np.pi),                # -Identity
        (12, 2 * np.pi / 5),            # Order 10, angle 2*pi/5
        (12, 4 * np.pi / 5),            # Order 10, angle 4*pi/5
        (12, 6 * np.pi / 5),            # Order 10, angle 6*pi/5
        (12, 8 * np.pi / 5),            # Order 10, angle 8*pi/5
        (20, 2 * np.pi / 3),            # Order 6, angle 2*pi/3
        (20, 4 * np.pi / 3),            # Order 6, angle 4*pi/3
        (30, np.pi),                    # Order 4, angle pi
    ]
    order = 120
    total = sum(s for s, _ in classes)
    assert total == order, f"I*: classes sum to {total}, expected {order}"
    return classes, order


# ===================================================================
# Molien series (trivial multiplicity) for each group type
# ===================================================================

def _multiplicity_from_classes(conjugacy_classes, group_order, k):
    """
    Compute r_Gamma(k) = dim of Gamma-invariant subspace in V_{k/2}.

    r_Gamma(k) = (1/|Gamma|) * sum_g chi_{k/2}(g)
               = (1/|Gamma|) * sum_{classes C} |C| * chi_{k/2}(theta_C)

    Parameters
    ----------
    conjugacy_classes : list of (size, theta)
    group_order : int
    k : int >= 0

    Returns
    -------
    int : multiplicity (guaranteed non-negative integer)
    """
    total = 0.0
    for size, theta in conjugacy_classes:
        chi = character_su2(k, theta)
        total += size * chi
    m = total / group_order
    m_int = int(round(m))
    if m_int < 0:
        # Can happen for very large k due to floating point; should be 0
        if abs(m) < 0.5:
            return 0
        raise ValueError(f"Negative multiplicity: k={k}, raw={m}")
    return m_int


def molien_cyclic(n, k_max):
    """
    Multiplicities r_{Z_n}(k) for k = 0, ..., k_max.

    For cyclic Z_n, the invariant subspace of V_{k/2} (dimension k+1)
    under the cyclic group generated by rotation 2*pi/n.

    Parameters
    ----------
    n : int >= 1
        Order of cyclic group. Z_1 = trivial group (full S^3).
    k_max : int
        Maximum level.

    Returns
    -------
    ndarray of int, shape (k_max+1,)
    """
    classes, order = conjugacy_classes_cyclic(n)
    result = np.zeros(k_max + 1, dtype=int)
    for k in range(k_max + 1):
        result[k] = _multiplicity_from_classes(classes, order, k)
    return result


def molien_binary_dihedral(n, k_max):
    """
    Multiplicities r_{D*_n}(k) for k = 0, ..., k_max.

    Parameters
    ----------
    n : int >= 2
        Index in D*_n. Group order is 4n.
    k_max : int
        Maximum level.

    Returns
    -------
    ndarray of int, shape (k_max+1,)
    """
    classes, order = conjugacy_classes_binary_dihedral(n)
    result = np.zeros(k_max + 1, dtype=int)
    for k in range(k_max + 1):
        result[k] = _multiplicity_from_classes(classes, order, k)
    return result


def molien_binary_tetrahedral(k_max):
    """
    Multiplicities r_{T*}(k) for k = 0, ..., k_max.

    Returns
    -------
    ndarray of int, shape (k_max+1,)
    """
    classes, order = conjugacy_classes_binary_tetrahedral()
    result = np.zeros(k_max + 1, dtype=int)
    for k in range(k_max + 1):
        result[k] = _multiplicity_from_classes(classes, order, k)
    return result


def molien_binary_octahedral(k_max):
    """
    Multiplicities r_{O*}(k) for k = 0, ..., k_max.

    Returns
    -------
    ndarray of int, shape (k_max+1,)
    """
    classes, order = conjugacy_classes_binary_octahedral()
    result = np.zeros(k_max + 1, dtype=int)
    for k in range(k_max + 1):
        result[k] = _multiplicity_from_classes(classes, order, k)
    return result


def molien_binary_icosahedral(k_max):
    """
    Multiplicities r_{I*}(k) for k = 0, ..., k_max.

    Should match the known sequence: r(0)=1, r(1..11)=0, r(12)=1, ...

    Returns
    -------
    ndarray of int, shape (k_max+1,)
    """
    classes, order = conjugacy_classes_binary_icosahedral()
    result = np.zeros(k_max + 1, dtype=int)
    for k in range(k_max + 1):
        result[k] = _multiplicity_from_classes(classes, order, k)
    return result


# ===================================================================
# Group catalog
# ===================================================================

def build_group_catalog(k_max=200):
    """
    Build a catalog of all ADE subgroups with their multiplicities.

    Returns
    -------
    list of dict with keys:
        'name': str, human-readable name
        'order': int, |Gamma|
        'ade_type': str, 'cyclic', 'binary_dihedral', 'binary_tetrahedral',
                    'binary_octahedral', 'binary_icosahedral'
        'multiplicities': ndarray of int, shape (k_max+1,)
    """
    catalog = []

    # Cyclic groups
    for n in [2, 3, 4, 5, 6, 7, 8, 10, 12, 15, 20, 24, 30, 60, 120]:
        catalog.append({
            'name': f'Z_{n}',
            'order': n,
            'ade_type': 'cyclic',
            'multiplicities': molien_cyclic(n, k_max),
        })

    # Binary dihedral groups
    for n in [2, 3, 4, 5, 6, 8, 10]:
        catalog.append({
            'name': f'D*_{n}',
            'order': 4 * n,
            'ade_type': 'binary_dihedral',
            'multiplicities': molien_binary_dihedral(n, k_max),
        })

    # Binary tetrahedral
    catalog.append({
        'name': 'T*',
        'order': 24,
        'ade_type': 'binary_tetrahedral',
        'multiplicities': molien_binary_tetrahedral(k_max),
    })

    # Binary octahedral
    catalog.append({
        'name': 'O*',
        'order': 48,
        'ade_type': 'binary_octahedral',
        'multiplicities': molien_binary_octahedral(k_max),
    })

    # Binary icosahedral
    catalog.append({
        'name': 'I*',
        'order': 120,
        'ade_type': 'binary_icosahedral',
        'multiplicities': molien_binary_icosahedral(k_max),
    })

    return catalog


# ===================================================================
# Suppression ratio and C_l computation
# ===================================================================

def _get_camb_transfer(omega_tot=1.018, l_max=30):
    """
    Run CAMB for closed S^3 and extract transfer data.

    Returns
    -------
    dict with keys:
        'nu_vals': ndarray of int, eigenmode indices
        'delta_sq': dict {l: ndarray}, |Delta_l(nu)|^2 for each l
        'cls_s3': dict {l: D_l}, D_l for simply-connected S^3 in muK^2
    """
    if not HAS_CAMB:
        raise ImportError("CAMB not installed. Run: pip install camb")

    from .cmb_boltzmann import PLANCK_2018

    omega_k = 1.0 - omega_tot
    pars = camb.CAMBparams()
    pars.set_cosmology(
        H0=PLANCK_2018['H0'],
        ombh2=PLANCK_2018['ombh2'],
        omch2=PLANCK_2018['omch2'],
        omk=omega_k,
        tau=PLANCK_2018['tau'],
    )
    pars.InitPower.set_params(
        As=PLANCK_2018['As'],
        ns=PLANCK_2018['ns'],
    )
    pars.set_for_lmax(l_max + 50, lens_potential_accuracy=0)

    results = camb.get_results(pars)

    # Full D_l for S^3
    powers = results.get_cmb_power_spectra(
        params=None, CMB_unit='muK', raw_cl=False
    )
    total = powers['total']
    cls_s3 = {}
    for l in range(2, min(l_max + 1, total.shape[0])):
        cls_s3[l] = total[l, 0]

    # Transfer data
    transfer = results.get_cmb_transfer_data()
    q = transfer.q
    dq = q[1] - q[0]
    nu_vals = np.round(q / dq).astype(int)
    Delta_T = transfer.delta_p_l_k[0]  # Temperature transfer
    L = transfer.L

    delta_sq = {}
    for l_val in L:
        if l_val < 2 or l_val > l_max:
            continue
        l_idx = np.where(L == l_val)[0][0]
        delta_sq[int(l_val)] = Delta_T[l_idx, :] ** 2

    return {
        'nu_vals': nu_vals,
        'delta_sq': delta_sq,
        'cls_s3': cls_s3,
        'L': L,
    }


def compute_suppression(r_gamma, nu_vals, delta_sq):
    """
    Compute suppression ratio S_l for a given topology.

    S_l = [sum_nu T_l(nu)^2 * r_Gamma(k) * nu] / [sum_nu T_l(nu)^2 * nu^2]

    where k = nu - 1.

    Parameters
    ----------
    r_gamma : ndarray of int
        Multiplicities r_Gamma(k) for k = 0, ..., k_max.
    nu_vals : ndarray of int
        CAMB eigenmode indices.
    delta_sq : dict {l: ndarray}
        |Delta_l(nu)|^2 for each multipole l.

    Returns
    -------
    dict {l: S_l}
    """
    k_max = len(r_gamma) - 1
    ratios = {}

    for l, d2 in delta_sq.items():
        # S^3: all modes with weight nu^2
        c_s3 = np.sum(d2 * nu_vals ** 2)

        # S^3/Gamma: surviving modes with weight r_Gamma(k) * nu
        c_gamma = 0.0
        for j, nu in enumerate(nu_vals):
            k = nu - 1
            if 0 <= k <= k_max:
                mk = r_gamma[k]
                if mk > 0:
                    c_gamma += d2[j] * mk * nu

        ratios[l] = c_gamma / c_s3 if c_s3 > 0 else 0.0

    return ratios


def compute_cls_quotient(r_gamma, omega_tot=1.018, l_max=30, camb_data=None):
    """
    Compute C_l for the quotient S^3/Gamma.

    Parameters
    ----------
    r_gamma : ndarray of int
        Multiplicities r_Gamma(k).
    omega_tot : float
        Total density parameter.
    l_max : int
        Maximum multipole.
    camb_data : dict or None
        Pre-computed CAMB transfer data (from _get_camb_transfer).
        If None, CAMB is run.

    Returns
    -------
    dict {l: D_l} in muK^2
    """
    if camb_data is None:
        camb_data = _get_camb_transfer(omega_tot, l_max)

    suppression = compute_suppression(
        r_gamma, camb_data['nu_vals'], camb_data['delta_sq']
    )

    cls_s3 = camb_data['cls_s3']
    cls_gamma = {}

    # Apply suppression where we have CAMB transfer data
    computed_ls = sorted(suppression.keys())
    for l in range(2, l_max + 1):
        d_s3 = cls_s3.get(l, 0.0)
        if l in suppression:
            cls_gamma[l] = d_s3 * suppression[l]
        elif len(computed_ls) >= 2:
            # Interpolate S_l for missing l values
            below = [cl for cl in computed_ls if cl < l]
            above = [cl for cl in computed_ls if cl > l]
            if below and above:
                l_lo, l_hi = below[-1], above[0]
                frac = (l - l_lo) / (l_hi - l_lo)
                s_interp = suppression[l_lo] + frac * (suppression[l_hi] - suppression[l_lo])
            elif below:
                s_interp = suppression[below[-1]]
            elif above:
                s_interp = suppression[above[0]]
            else:
                s_interp = 1.0
            cls_gamma[l] = d_s3 * s_interp
        else:
            cls_gamma[l] = d_s3

    return cls_gamma


def scan_all_ade_groups(omega_tot=1.018, l_max=30, k_max=None):
    """
    Scan all ADE subgroups and compute D_2 for each.

    Parameters
    ----------
    omega_tot : float
        Total density parameter.
    l_max : int
        Maximum multipole.
    k_max : int or None
        Maximum eigenmode index for multiplicity computation.
        If None, determined from CAMB nu_vals (recommended).

    Returns
    -------
    list of dict with keys:
        'name': str
        'order': int
        'ade_type': str
        'D_2': float (muK^2)
        'D_3': float (muK^2)
        'S_2': float (suppression ratio at l=2)
        'first_nonzero': int (first k > 0 with r(k) > 0)
        'n_modes_50': int (number of nonzero r(k) for k <= 50)
    """
    camb_data = _get_camb_transfer(omega_tot, l_max)

    # Set k_max from CAMB if not specified
    if k_max is None:
        k_max = int(camb_data['nu_vals'][-1])

    catalog = build_group_catalog(k_max)

    results = []
    for group in catalog:
        r = group['multiplicities']
        cls = compute_cls_quotient(r, omega_tot, l_max, camb_data)

        # Find first nonzero mode after k=0
        first_nz = None
        for k in range(1, k_max + 1):
            if r[k] > 0:
                first_nz = k
                break

        # Count modes in low-k regime
        n_modes_50 = int(np.sum(r[1:51] > 0))

        sup = compute_suppression(r, camb_data['nu_vals'], camb_data['delta_sq'])

        results.append({
            'name': group['name'],
            'order': group['order'],
            'ade_type': group['ade_type'],
            'D_2': cls.get(2, 0.0),
            'D_3': cls.get(3, 0.0),
            'S_2': sup.get(2, 0.0),
            'first_nonzero': first_nz,
            'n_modes_50': n_modes_50,
        })

    return results


def find_best_topology(target_d2=201.0, omega_tot_range=(1.001, 1.05),
                       n_omega=20, l_max=30, k_max=None):
    """
    Find (Gamma, Omega_tot) that gives D_2 closest to target.

    Scans a grid of Omega_tot values for each ADE group.

    Parameters
    ----------
    target_d2 : float
        Target D_2 in muK^2 (default: Planck 201).
    omega_tot_range : tuple
        Range of Omega_tot to scan.
    n_omega : int
        Number of Omega_tot values to try.
    l_max : int
        Maximum multipole.
    k_max : int or None
        Maximum eigenmode index. If None, determined from first CAMB run.

    Returns
    -------
    list of dict sorted by |D_2 - target|, with keys:
        'name', 'order', 'omega_tot', 'D_2', 'D_3', 'delta_d2'
    """
    omega_values = np.linspace(omega_tot_range[0], omega_tot_range[1], n_omega)

    # Build catalog once (at the largest k_max we'll need)
    # Use first omega_tot to determine k_max from CAMB, then reuse catalog
    catalog = None

    all_results = []

    for omega_tot in omega_values:
        try:
            camb_data = _get_camb_transfer(omega_tot, l_max)
        except Exception:
            continue

        if catalog is None:
            if k_max is None:
                k_max = int(camb_data['nu_vals'][-1])
            catalog = build_group_catalog(k_max)

        for group in catalog:
            r = group['multiplicities']
            cls = compute_cls_quotient(r, omega_tot, l_max, camb_data)
            d2 = cls.get(2, 0.0)
            d3 = cls.get(3, 0.0)

            all_results.append({
                'name': group['name'],
                'order': group['order'],
                'omega_tot': omega_tot,
                'D_2': d2,
                'D_3': d3,
                'delta_d2': abs(d2 - target_d2),
            })

    # Sort by |D_2 - target|
    all_results.sort(key=lambda x: x['delta_d2'])
    return all_results


# ===================================================================
# Pretty-printing
# ===================================================================

def print_scan_results(results, target_d2=201.0):
    """
    Print scan results as a formatted table.

    Parameters
    ----------
    results : list of dict from scan_all_ade_groups
    target_d2 : float
    """
    # Sort by |D_2 - target|
    sorted_results = sorted(results, key=lambda x: abs(x['D_2'] - target_d2))

    header = f"{'Group':<12} {'|G|':>5} {'Type':<20} {'D_2 (uK^2)':>12} {'|D_2-201|':>10} {'S_2':>8} {'1st k>0':>8} {'modes<50':>9}"
    print(header)
    print("-" * len(header))

    for r in sorted_results:
        first_nz = r['first_nonzero'] if r['first_nonzero'] is not None else '-'
        print(f"{r['name']:<12} {r['order']:>5} {r['ade_type']:<20} "
              f"{r['D_2']:>12.2f} {abs(r['D_2'] - target_d2):>10.2f} "
              f"{r['S_2']:>8.4f} {str(first_nz):>8} {r['n_modes_50']:>9}")
